Feature/hero-img/Add hero image
kacus/CC-porfolio pull request #1
Opened 2020-11-27 18:19 UTC by kacus

2020-11-27 20:13 UTC, Skorcese requested changes

2020-11-27 20:13 UTC, Skorcese commented on index.html
> +        <div class="hero__logo">
The title is not centered on all viewports. That's caused by .hero__logo content overflowing their span container due to **letter-spacing: -1rem;**

You can either set the letter spacing to positive values and adjust the position of characters manually, or move the whole section with transform: translateX(...);

![image](https://user-images.githubusercontent.com/56897157/100480878-d04f2a00-30f2-11eb-8822-0fef9e429b65.png)

![image](https://user-images.githubusercontent.com/56897157/100481472-72bbdd00-30f4-11eb-9e2f-55e5761c1f83.png)

2020-11-27 20:13 UTC, Skorcese commented on style.css
> +
I can see you are using relative units already, but this trick could let you measure rems in relation to pixels - 1:1

html{
font-size: 62.5%;
}

body{
font-size: 1.6rem;
}

This way you can write 123px as 12.3rem for example
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size

2020-11-27 20:13 UTC, Skorcese commented on style.css
> +@media screen and (min-width: 480px) {
@media screen and (min-width: 480px) and (orientation: landscape) { ... }

2020-11-27 20:13 UTC, Skorcese commented on style.css
> +@media screen and (min-width: 768px) {
@media screen and (min-width: 768px) and (orientation: portrait) { ... }

2020-11-27 20:13 UTC, Skorcese commented on style.css
> +@media screen and (min-width: 992px) {
@media screen and (min-width: 992px) and (orientation: landscape) { ... }

2020-11-28 16:11 UTC, kacus commented on index.html
> +        <div class="hero__logo">
solved in #feee4f40d19ce893160a45df59c315c715572e10

2020-11-28 16:14 UTC, kacus commented on style.css
> +@media screen and (min-width: 480px) {
Solved in https://github.com/kacus/CC-porfolio/pull/1/commits/28f4bdbb60da2ef0c06a166ff99fd95f88609892

2020-11-28 16:14 UTC, kacus commented on style.css
> +@media screen and (min-width: 768px) {
Solved in https://github.com/kacus/CC-porfolio/pull/1/commits/28f4bdbb60da2ef0c06a166ff99fd95f88609892

2020-11-28 16:15 UTC, kacus commented on style.css
> +@media screen and (min-width: 992px) {
Solved in https://github.com/kacus/CC-porfolio/pull/1/commits/28f4bdbb60da2ef0c06a166ff99fd95f88609892

2020-11-29 13:14 UTC, merged